--Kiểm tra xem database đã tồn tại hay chưa, tồn tại thì xóa
IF EXISTS (SELECT * FROM sys.databases WHERE name = N'[dbQUANLYBANHANG]')
BEGIN
    -- Đóng tất cả các kết nối đến cơ sở dữ liệu
    EXECUTE sp_MSforeachdb 'IF ''?'' = ''[dbQUANLYBANHANG]'' 
    BEGIN
        DECLARE @sql AS NVARCHAR(MAX) = ''USE [?]; ALTER DATABASE [?] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;''
        EXEC (@sql)
    END'
    -- Xóa tất cả các kết nối tới cơ sở dữ liệu (thực hiện qua hệ thống master)
    USE master;

    -- Xóa cơ sở dữ liệu nếu tồn tại
    DROP DATABASE [dbQUANLYBANHANG];
END
go
--tạo database tên "QLBH" - Quản lý bán hàng
create database [dbQUANLYBANHANG];

go
 
USE [dbQUANLYBANHANG]
GO
/****** Object:  Table [dbo].[APPLICATIONS]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATIONS](
	[ID_APPLICATION] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[APPLICATION_NAME] [nvarchar](100) NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
 CONSTRAINT [PK_APPLICATIONS] PRIMARY KEY CLUSTERED 
(
	[ID_APPLICATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[APPLICATIONS_MENU_FORM_RELATIONS]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS](
	[ID_MENU_FORM] [numeric](18, 0) NOT NULL,
	[ID_APPLICATION] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_APPLICATIONS_MENU_FORM_RELATIONS] PRIMARY KEY CLUSTERED 
(
	[ID_MENU_FORM] ASC,
	[ID_APPLICATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[GENDER]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GENDER](
	[PARTY_ID] [numeric](18, 0) NOT NULL,
	[GENDER_TYPE_ID] [numeric](18, 0) NOT NULL,
	[FROM_DATE] [datetime] NOT NULL,
	[THRU_DATE] [datetime] NULL,
 CONSTRAINT [PK__GENDER__3F865F66] PRIMARY KEY CLUSTERED 
(
	[PARTY_ID] ASC,
	[GENDER_TYPE_ID] ASC,
	[FROM_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[GENDER_TYPE]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GENDER_TYPE](
	[GENDER_TYPE_ID] [numeric](18, 0) NOT NULL,
	[GENDER_TYPE_NAME] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK__GENDER_TYPE__3D9E16F4] PRIMARY KEY CLUSTERED 
(
	[GENDER_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GROUP_RELATIONSHIP_MENU_FORM]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM](
	[PARTY_ID] [numeric](18, 0) NOT NULL,
	[ID_GROUP] [numeric](18, 0) NOT NULL,
	[ID_MENU_FORM] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_GROUP_RELATIONSHIP_MENU_FORM] PRIMARY KEY CLUSTERED 
(
	[PARTY_ID] ASC,
	[ID_GROUP] ASC,
	[ID_MENU_FORM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[GROUP_USER]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_USER](
	[ID_GROUP] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[GROUP_NAME] [nvarchar](300) NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
 CONSTRAINT [PK_GROUP_USER] PRIMARY KEY CLUSTERED 
(
	[ID_GROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[GROUP_USER_RELATIONSHIP_USER]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER](
	[PARTY_ID] [numeric](18, 0) NOT NULL,
	[ID_GROUP] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_GROUP_USER_RELATIONSHIP_USER_1] PRIMARY KEY CLUSTERED 
(
	[PARTY_ID] ASC,
	[ID_GROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MENU_FORM]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MENU_FORM](
	[ID_MENU_FORM] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[MENU_FORM_NAME] [nvarchar](300) NULL,
	[MENU_FORM_URL] [varchar](50) NULL,
	[MOTA] [nvarchar](500) NULL,
	[SORT_PARENT] [tinyint] NULL,
	[SORT] [tinyint] NULL,
	[ID_MENU_FORM_PARENT] [numeric](18, 0) NULL,
	[DANH_MUC] [bit] NULL,
	[VISIBLE] [bit] NULL,
 CONSTRAINT [PK_MENU_FORM] PRIMARY KEY CLUSTERED 
(
	[ID_MENU_FORM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PARTY]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTY](
	[PARTY_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TYPE_OF_PARTY] [nvarchar](50) NOT NULL,
	[DEPARTMENT_ID] [int] NULL,
	[USERNAME] [nvarchar](20) NULL,
	[PASSWORD] [nvarchar](20) NULL,
	[USERNAME_H] [nvarchar](300) NULL,
	[PASSWORD_H] [nvarchar](300) NULL,
 CONSTRAINT [PK_PARTY_1] PRIMARY KEY CLUSTERED 
(
	[PARTY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PERSON]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSON](
	[PARTY_ID] [numeric](18, 0) NOT NULL,
	[CURRENT_LAST_NAME] [nvarchar](50) NULL,
	[CURRENT_FIRST_NAME] [nvarchar](50) NULL,
	[CURRENT_MIDDLE_NAME] [nvarchar](50) NULL,
	[CURRENT_NICKNAME] [nvarchar](50) NULL,
	[CURRENT_GENDER_TYPE_ID] [numeric](18, 0) NULL,
	[BIRTH_DATE] [datetime] NULL,
	[PEOPLE_ID_NUMBER] [nvarchar](50) NULL,
	[PEOPLE_ID_ISSUE_DATE] [datetime] NULL,
	[PEOPLE_ID_ISSUE_PLACE] [nvarchar](50) NULL,
	[CURRENT_PHONE_NUMBER] [nvarchar](100) NULL,
	[CURRENT_EMAIL] [nvarchar](100) NULL,
	[PERSON_IMAGE] [nvarchar](50) NULL,
 CONSTRAINT [PK_PERSON] PRIMARY KEY CLUSTERED 
(
	[PARTY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbCHITIETHOADON]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCHITIETHOADON](
	[MACHITIET] [int] IDENTITY(1,1) NOT NULL,
	[MASANPHAM] [int] NULL,
	[SOLUONG] [numeric](18, 0) NULL,
	[DONGIA] [numeric](18, 0) NULL,
	[MAHOADON] [int] NULL,
 CONSTRAINT [PK_tbCHITIETHOADON] PRIMARY KEY CLUSTERED 
(
	[MACHITIET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbDANHMUC]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbDANHMUC](
	[MADANHMUC] [int] IDENTITY(1,1) NOT NULL,
	[TENDANHMUC] [nvarchar](200) NULL,
	[DANHMUCCHA] [int] NULL,
	[MOTA] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[MADANHMUC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbHOADON]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbHOADON](
	[MAHOADON] [int] NOT NULL,
	[MAKHACHHANG] [numeric](18, 0) NULL,
	[NGAY] [datetime] NULL,
	[TONGTIEN] [numeric](18, 0) NULL,
 CONSTRAINT [PK_tbHOADON] PRIMARY KEY CLUSTERED 
(
	[MAHOADON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbKHANHHANG]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbKHANHHANG](
	[MAKHACHHANG] [numeric](18, 0) NOT NULL,
	[HOTEN] [nvarchar](50) NULL,
	[NGAYSINH] [date] NULL,
	[GIOITINH] [nvarchar](6) NULL,
	[EMAIL] [nchar](10) NULL,
	[DIACHI] [nvarchar](200) NULL,
	[TAIKHOAN] [nvarchar](50) NULL,
	[MATKHAU] [nvarchar](50) NULL,
 CONSTRAINT [PK_tbKHANHHANG] PRIMARY KEY CLUSTERED 
(
	[MAKHACHHANG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbSANPHAM]    Script Date: 20/09/2023 2:22:06 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbSANPHAM](
	[MASANPHAM] [int] IDENTITY(1,1) NOT NULL,
	[TENSANPHAM] [nvarchar](200) NULL,
	[DONGIA] [numeric](18, 0) NULL,
	[SOLUONG] [numeric](18, 0) NULL,
	[HINHANH] [nvarchar](50) NULL,
	[MOTA] [nvarchar](max) NULL,
	[MADANHMUC] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MASANPHAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[tbDANHMUC] ON 

GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (1, N'Máy vi tính', 0, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (2, N'LapTop', 1, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (3, N'Điện Thoại', 0, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (4, N'Iphome', 2, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (5, N'SamSung', 2, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (6, N'Ti vi', 0, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (7, N'Sony', 5, NULL)
GO
SET IDENTITY_INSERT [dbo].[tbDANHMUC] OFF
GO
SET IDENTITY_INSERT [dbo].[tbSANPHAM] ON 

GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH], [MOTA], [MADANHMUC]) VALUES (7, N'Laptop Dell Vostro 3420 I5', CAST(2000 AS Numeric(18, 0)), CAST(10 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 8MB)
RAM: 8GB(8GBx1) DDR4 3200MHz (2 khe)
Ổ cứng: 256GB M.2 256GB PCIe NVMe + 1x2.5"(HDD/SSD)
VGA: Intel Iris Xe Graphics', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH], [MOTA], [MADANHMUC]) VALUES (8, N'THINKPAD W510 i7 EXTREME', CAST(300 AS Numeric(18, 0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 8MB)
RAM: 8GB(8GBx1) DDR4 3200MHz (2 khe)
Ổ cứng: 256GB M.2 256GB PCIe NVMe + 1x2.5"(HDD/SSD)
VGA: Intel Iris Xe Graphics', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH], [MOTA], [MADANHMUC]) VALUES (9, N'THINKPAD W510 i7 EXTREME', CAST(300 AS Numeric(18, 0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH], [MOTA], [MADANHMUC]) VALUES (10, N'THINKPAD W510 i7 EXTREME', CAST(500 AS Numeric(18, 0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH], [MOTA], [MADANHMUC]) VALUES (11, N'Laptop Dell Vostro 3420 I5', CAST(300 AS Numeric(18, 0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH], [MOTA], [MADANHMUC]) VALUES (12, N'Laptop Dell Vostro 3420 I5', CAST(100 AS Numeric(18, 0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH], [MOTA], [MADANHMUC]) VALUES (53, N'Samsung z10', CAST(430000 AS Numeric(18, 0)), CAST(111 AS Numeric(18, 0)), N'SAMSUNG2.jfif', N'Thiáº¿t káº¿ tá»i giáº£n nhÆ°ng khÃ´ng kÃ©m pháº§n hÃºt máº¯t
ÄÃ¡p á»©ng tá»t má»i tÃ¡c vá»¥ hÃ ng ngÃ y
KhÃ¡m phÃ¡ má»i thá»© nhá» cá»¥m camera áº¥n tÆ°á»£ng
Tráº£i nghiá»m ngÃ y dÃ i, khÃ´ng lo vá» pin', 3)
GO
SET IDENTITY_INSERT [dbo].[tbSANPHAM] OFF
GO
ALTER TABLE [dbo].[MENU_FORM] ADD  CONSTRAINT [DF_MENU_FORM_DANH_MUC]  DEFAULT ((0)) FOR [DANH_MUC]
GO
ALTER TABLE [dbo].[MENU_FORM] ADD  CONSTRAINT [DF_MENU_FORM_VISIBLE]  DEFAULT ((1)) FOR [VISIBLE]
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATIONS_MENU_FORM_RELATIONS_APPLICATIONS] FOREIGN KEY([ID_APPLICATION])
REFERENCES [dbo].[APPLICATIONS] ([ID_APPLICATION])
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS] CHECK CONSTRAINT [FK_APPLICATIONS_MENU_FORM_RELATIONS_APPLICATIONS]
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATIONS_MENU_FORM_RELATIONS_MENU_FORM] FOREIGN KEY([ID_MENU_FORM])
REFERENCES [dbo].[MENU_FORM] ([ID_MENU_FORM])
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS] CHECK CONSTRAINT [FK_APPLICATIONS_MENU_FORM_RELATIONS_MENU_FORM]
GO
ALTER TABLE [dbo].[GENDER]  WITH CHECK ADD  CONSTRAINT [ FK__GENDER__GENDER_T__416EA7D8] FOREIGN KEY([GENDER_TYPE_ID])
REFERENCES [dbo].[GENDER_TYPE] ([GENDER_TYPE_ID])
GO
ALTER TABLE [dbo].[GENDER] CHECK CONSTRAINT [ FK__GENDER__GENDER_T__416EA7D8]
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_RELATIONSHIP_MENU_FORM_GROUP_USER_RELATIONSHIP_USER] FOREIGN KEY([PARTY_ID], [ID_GROUP])
REFERENCES [dbo].[GROUP_USER_RELATIONSHIP_USER] ([PARTY_ID], [ID_GROUP])
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM] CHECK CONSTRAINT [FK_GROUP_RELATIONSHIP_MENU_FORM_GROUP_USER_RELATIONSHIP_USER]
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_RELATIONSHIP_MENU_FORM_MENU_FORM] FOREIGN KEY([ID_MENU_FORM])
REFERENCES [dbo].[MENU_FORM] ([ID_MENU_FORM])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM] CHECK CONSTRAINT [FK_GROUP_RELATIONSHIP_MENU_FORM_MENU_FORM]
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_USER_RELATIONSHIP_USER_GROUP_USER] FOREIGN KEY([ID_GROUP])
REFERENCES [dbo].[GROUP_USER] ([ID_GROUP])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER] CHECK CONSTRAINT [FK_GROUP_USER_RELATIONSHIP_USER_GROUP_USER]
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_USER_RELATIONSHIP_USER_PARTY] FOREIGN KEY([PARTY_ID])
REFERENCES [dbo].[PARTY] ([PARTY_ID])
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER] CHECK CONSTRAINT [FK_GROUP_USER_RELATIONSHIP_USER_PARTY]
GO
ALTER TABLE [dbo].[MENU_FORM]  WITH CHECK ADD  CONSTRAINT [FK_MENU_FORM_MENU_FORM] FOREIGN KEY([ID_MENU_FORM_PARENT])
REFERENCES [dbo].[MENU_FORM] ([ID_MENU_FORM])
GO
ALTER TABLE [dbo].[MENU_FORM] CHECK CONSTRAINT [FK_MENU_FORM_MENU_FORM]
GO
ALTER TABLE [dbo].[PERSON]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_PARTY] FOREIGN KEY([PARTY_ID])
REFERENCES [dbo].[PARTY] ([PARTY_ID])
GO
ALTER TABLE [dbo].[PERSON] CHECK CONSTRAINT [FK_PERSON_PARTY]
GO
ALTER TABLE [dbo].[tbCHITIETHOADON]  WITH CHECK ADD  CONSTRAINT [FK_tbCHITIETHOADON_tbHOADON] FOREIGN KEY([MAHOADON])
REFERENCES [dbo].[tbHOADON] ([MAHOADON])
GO
ALTER TABLE [dbo].[tbCHITIETHOADON] CHECK CONSTRAINT [FK_tbCHITIETHOADON_tbHOADON]
GO
ALTER TABLE [dbo].[tbCHITIETHOADON]  WITH CHECK ADD  CONSTRAINT [FK_tbCHITIETHOADON_tbSANPHAM] FOREIGN KEY([MASANPHAM])
REFERENCES [dbo].[tbSANPHAM] ([MASANPHAM])
GO
ALTER TABLE [dbo].[tbCHITIETHOADON] CHECK CONSTRAINT [FK_tbCHITIETHOADON_tbSANPHAM]
GO
ALTER TABLE [dbo].[tbHOADON]  WITH CHECK ADD  CONSTRAINT [FK_tbHOADON_PARTY] FOREIGN KEY([MAKHACHHANG])
REFERENCES [dbo].[PARTY] ([PARTY_ID])
GO
ALTER TABLE [dbo].[tbHOADON] CHECK CONSTRAINT [FK_tbHOADON_PARTY]
GO
ALTER TABLE [dbo].[tbHOADON]  WITH CHECK ADD  CONSTRAINT [FK_tbHOADON_tbKHANHHANG] FOREIGN KEY([MAKHACHHANG])
REFERENCES [dbo].[tbKHANHHANG] ([MAKHACHHANG])
GO
ALTER TABLE [dbo].[tbHOADON] CHECK CONSTRAINT [FK_tbHOADON_tbKHANHHANG]
GO
ALTER TABLE [dbo].[tbSANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_tbSANPHAM_tbDANHMUC] FOREIGN KEY([MADANHMUC])
REFERENCES [dbo].[tbDANHMUC] ([MADANHMUC])
GO
ALTER TABLE [dbo].[tbSANPHAM] CHECK CONSTRAINT [FK_tbSANPHAM_tbDANHMUC]
GO

CREATE PROC dbo.psGetTableSANPHAM
    @MASANPHAM INT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRAN;

    IF (@MASANPHAM IS NULL)
        SELECT * FROM tbSANPHAM;
    ELSE
        SELECT * FROM tbSANPHAM WHERE MASANPHAM = @MASANPHAM;

    IF (@@ERROR <> 0)
        ROLLBACK TRAN;
    ELSE
        COMMIT TRAN;
END
GO
-- Xóa thủ tục cũ đi để tránh lỗi
DROP PROCEDURE IF EXISTS psGetTableDANHMUC;
GO

-- Tạo lại thủ tục với câu SELECT đã được sửa, bỏ đi transaction không cần thiết
CREATE PROC [dbo].[psGetTableDANHMUC] (@MADANHMUC INT)
AS
BEGIN
    SET NOCOUNT ON; -- Thêm dòng này để không trả về thông báo "(x rows affected)"

    IF(@MADANHMUC IS NULL)
        -- Sửa lại: Dùng SELECT * để lấy tất cả các cột khớp với model
        SELECT * FROM tbDANHMUC;
    ELSE
        SELECT * FROM tbDANHMUC WHERE MADANHMUC = @MADANHMUC;
END
GO
create proc [dbo].[psGetTableLOGIN] (@USERNAME nvarchar(30), @PASSWORD nvarchar(30))
AS
BEGIN TRAN
SELECT * FROM PARTY WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD
IF(@@ERROR <> 0)
	ROLLBACK TRAN
ELSE
	COMMIT TRAN

GO
CREATE proc [dbo].[psInsertRecordSANPHAM] (@TENSANPHAM NVARCHAR(300),
    @DONGIA numeric(18, 0),
    @SOLUONG INT,
    @HINHANH nvarchar(50),
    @MOTA nvarchar(MAX),
    @MADANHMUC INT)
AS
BEGIN TRAN

    INSERT INTO tbSANPHAM(TENSANPHAM, DONGIA, SOLUONG, HINHANH, MOTA, MADANHMUC)
    VALUES(@TENSANPHAM, @DONGIA, @SOLUONG, @HINHANH, @MOTA, @MADANHMUC)

    IF(@@ERROR<>0)
        ROLLBACK TRAN
    ELSE
        COMMIT TRAN

GO
Create proc [dbo].[psUpdateRecordSANPHAM](
    @MASANPHAM INT,
    @TENSANPHAM NVARCHAR(300),
    @DONGIA numeric(18, 0),
    @SOLUONG INT,
    @HINHANH nvarchar(50),
    @MOTA nvarchar(MAX),
    @MADANHMUC INT
)
AS
BEGIN TRAN
    UPDATE tbSANPHAM 
    SET TENSANPHAM = @TENSANPHAM,
        DONGIA = @DONGIA,
        SOLUONG = @SOLUONG,
        HINHANH = @HINHANH,
        MOTA = @MOTA,
        MADANHMUC = @MADANHMUC
    WHERE MASANPHAM = @MASANPHAM

    IF(@@ERROR<>0)
        ROLLBACK TRAN
    ELSE
        COMMIT TRAN

GO
Create proc [dbo].[psDeleteRecordSANPHAM](@MASANPHAM INT)
AS
BEGIN TRAN

	DELETE FROM tbSANPHAM WHERE MASANPHAM = @MASANPHAM

    IF(@@ERROR<>0)
        ROLLBACK TRAN
    ELSE
        COMMIT TRAN

GO
-- Kiểm tra nếu thủ tục đã tồn tại thì xóa đi để tạo lại cho chắc chắn
IF OBJECT_ID('psGetTableSANPHAM_ByDanhMuc', 'P') IS NOT NULL
    DROP PROCEDURE psGetTableSANPHAM_ByDanhMuc;
GO

-- Tạo lại Stored Procedure
CREATE PROC [dbo].[psGetTableSANPHAM_ByDanhMuc] (@MADANHMUC INT)
AS
BEGIN
    SET NOCOUNT ON; -- Không trả về số dòng bị ảnh hưởng
    SELECT * FROM tbSANPHAM WHERE MADANHMUC = @MADANHMUC;
END


--NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----NOTE----
-- ========================================================
-- PHẦN 1: XÓA CÁC ĐỐI TƯỢNG CŨ NẾU TỒN TẠI
-- ========================================================

PRINT 'Kiểm tra và xóa các Stored Procedures cũ...';
IF OBJECT_ID('dbo.sp_UpdateCartQuantity', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_UpdateCartQuantity;
GO
IF OBJECT_ID('dbo.sp_RemoveFromCart', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_RemoveFromCart;
GO
IF OBJECT_ID('dbo.sp_AddToCart', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_AddToCart;
GO
IF OBJECT_ID('dbo.sp_GetCart_ByCustomerId', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_GetCart_ByCustomerId;
GO

PRINT 'Kiểm tra và xóa bảng tbGIOHANG cũ...';
IF OBJECT_ID('dbo.tbGIOHANG', 'U') IS NOT NULL
    DROP TABLE dbo.tbGIOHANG;
GO

-- ========================================================
-- PHẦN 2: TẠO LẠI BẢNG VÀ STORED PROCEDURES
-- ========================================================

-- Bước 1: Tạo lại bảng tbGIOHANG với khóa ngoại trỏ đến PARTY
PRINT 'Đang tạo lại bảng tbGIOHANG...';
CREATE TABLE dbo.tbGIOHANG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MAKHACHHANG NUMERIC(18, 0) NOT NULL,
    MASANPHAM INT NOT NULL,
    SOLUONG INT NOT NULL,
    -- <<< THAY ĐỔI QUAN TRỌNG: Khóa ngoại giờ trỏ đến bảng PARTY >>>
    CONSTRAINT FK_GIOHANG_PARTY FOREIGN KEY (MAKHACHHANG) REFERENCES dbo.PARTY(PARTY_ID),
    CONSTRAINT FK_GIOHANG_SANPHAM FOREIGN KEY (MASANPHAM) REFERENCES dbo.tbSANPHAM(MASANPHAM)
);
GO
PRINT 'Hoàn tất tạo bảng tbGIOHANG.';
GO


-- Bước 2: Tạo lại Stored Procedures cho Giỏ hàng
PRINT 'Đang tạo lại Stored Procedures cho Giỏ hàng...';
GO

-- Lấy giỏ hàng theo mã khách hàng (PARTY_ID)
CREATE PROCEDURE sp_GetCart_ByCustomerId
    @MaKhachHang NUMERIC(18, 0)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        gh.MASANPHAM,
        gh.SOLUONG,
        sp.TENSANPHAM,
        sp.DONGIA,
        sp.HINHANH
    FROM dbo.tbGIOHANG gh
    JOIN dbo.tbSANPHAM sp ON gh.MASANPHAM = sp.MASANPHAM
    WHERE gh.MAKHACHHANG = @MaKhachHang;
END
GO

-- Thêm vào giỏ hàng (hoặc cập nhật số lượng nếu đã tồn tại)
CREATE PROCEDURE sp_AddToCart
    @MaKhachHang NUMERIC(18, 0),
    @MaSanPham INT,
    @SoLuong INT
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM dbo.tbGIOHANG WHERE MAKHACHHANG = @MaKhachHang AND MASANPHAM = @MaSanPham)
    BEGIN
        UPDATE dbo.tbGIOHANG
        SET SOLUONG = SOLUONG + @SoLuong
        WHERE MAKHACHHANG = @MaKhachHang AND MASANPHAM = @MaSanPham;
    END
    ELSE
    BEGIN
        INSERT INTO dbo.tbGIOHANG (MAKHACHHANG, MASANPHAM, SOLUONG)
        VALUES (@MaKhachHang, @MaSanPham, @SoLuong);
    END
END
GO

-- Xóa một sản phẩm khỏi giỏ hàng
CREATE PROCEDURE sp_RemoveFromCart
    @MaKhachHang NUMERIC(18, 0),
    @MaSanPham INT
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM dbo.tbGIOHANG
    WHERE MAKHACHHANG = @MaKhachHang AND MASANPHAM = @MaSanPham;
END
GO

-- Cập nhật số lượng của một sản phẩm trong giỏ
CREATE PROCEDURE sp_UpdateCartQuantity
    @MaKhachHang NUMERIC(18, 0),
    @MaSanPham INT,
    @SoLuong INT
AS
BEGIN
    SET NOCOUNT ON;
    IF (@SoLuong > 0)
    BEGIN
        UPDATE dbo.tbGIOHANG
        SET SOLUONG = @SoLuong
        WHERE MAKHACHHANG = @MaKhachHang AND MASANPHAM = @MaSanPham;
    END
    ELSE
    BEGIN
        DELETE FROM dbo.tbGIOHANG
        WHERE MAKHACHHANG = @MaKhachHang AND MASANPHAM = @MaSanPham;
    END
END
GO

PRINT 'Hoàn tất tạo Stored Procedures cho Giỏ hàng.';
GO